[project]
name = "bdut-projectfinal"
version = "0.1.0"
authors = ["Verbytsky Pavel <p.verbytsky@gmail.com>", "Shuvarynska Sofia <sofiaradisna@gmail.com>", "Kalantarchuk Ivan <kalantarcukvana@gmail.com>"]

